name: Build Docker Image

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository to the runner
    - name: Check out the repository
      uses: actions/checkout@v3

    # Set up Docker Buildx (optional, but useful for multi-platform builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub (optional, if you want to push the image)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        #Curentlly this secrets are at, https://github.com/AleksandarKosev/pacman/settings/secrets/actions
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image
    - name: Build the Docker image
      run: |
        docker build -f Dockerfile -t ${{ github.actor }}/pacman:SimSectorStudioBuild . --build-arg VERSION=1

    